### ISSUE TITLE
Release on Maven Central

### ISSUE THREAD

**Issue by Wavesonics** [shouldit/android-proxy#3]
It'd be great to get a release of this on Maven Central.

**Comment by olifozzy** [comment]
Hi,
I'd like to be able to import the APL in my project in AndroidStudio with gradle.

I've added the following line in my build.gradle : 

compile 'be.shouldit:android-proxy-library:4.0.0'

But I have an error when I sync it:

Unrecognized dependency: 'be.shouldit:android-proxy-library:4.0.0' (type: 'aar.asc', extension: 'aar.asc')

Accoriding to that post: http://stackoverflow.com/questions/21942727/gradle-only-downloads-aar-asc-from-maven-central  it might come from the way you publish/packae the library ..

PS: i'm a noob at all that so I might have totally missed something ....

Any clues ?
Thanks

**Comment by lechuckcaptain** [comment]
You are right. There is definitely a bug on my upload script.

**Comment by lechuckcaptain** [comment]
Fixed by 798bc80ca6650aed54d33a4918b4b4d63650b892

**Comment by olifozzy** [comment]
Thanks, It works fine now !

**Comment by LiJohnson** [comment]
```sql
select * from abs
```
